id: I0C686409
legacy_id: P003209
ocr_import_info:
  bdrc_scan_id: W2CZ7907
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T12:50:37'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:27:46.004746+00:00'
last_modified: 2022-09-02 23:27:56.754451
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ7907
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ7907
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཤེས་རབ་དཔལ་གྱི་དྲིས་ལན།
  author: བྱང་པ་རྣམ་རྒྱལ་གྲགས་པ་བཟང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.5565307032331951
  ocr_word_median_confidence_index: 0.550000011920929
quality: null
bases:
  I1KG3185:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3185
      total_pages: 66
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3185.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5565307032331951
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
