id: I0C686409
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:51:07+00:00'
last_modified: '2022-06-07T18:24:34.317603+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ7907
  title: ཤེས་རབ་དཔལ་གྱི་དྲིས་ལན་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7FF2:
      image_group_id: I1KG3185
      title: ''
      total_pages: 66
      order: 1
      base_file: 7FF2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
