id: P003209
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ7907
  title: ཤེས་རབ་དཔལ་གྱི་དྲིས་ལན་
  author: ''
  volumes:
    58fba93ff61149f8ba32fef737b2f198:
      image_group_id: I1KG3185
      title: ''
      volume_number: 1
      total_pages: 66
      base_file: v001.txt
